DROP TABLE IF EXISTS COUNTRY_STATE;
DROP TABLE IF EXISTS STATE_CITY;
DROP TABLE IF EXISTS CITY_LOCALITY;

DROP TABLE IF EXISTS POST_RESOURCE;
DROP TABLE IF EXISTS POST;

DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS STATE;
DROP TABLE IF EXISTS CITY;
DROP TABLE IF EXISTS LOCALITY;