create table NAME
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE_ID BIGINT NOT NULL,
  FIRST_NAME VARCHAR(1024) NOT NULL,
  MIDDLE_NAME VARCHAR(1024) NOT NULL,
  LAST_NAME VARCHAR(1024) NOT NULL,
  PREFERRED_NAME VARCHAR(1024) NOT NULL,
  LAST_UPDATED_DATE DATE,
  constraint NAME primary key (ID)
)
;

ALTER TABLE NAME ADD FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
;

create table ADDRESS
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LINE1 VARCHAR(1024) NOT NULL,
  LINE2 VARCHAR(1024) NOT NULL,
  LINE3 VARCHAR(1024) NOT NULL,
  CITY VARCHAR(1024) NOT NULL,
  COUNTY VARCHAR(1024) NOT NULL,
  POST_CODE VARCHAR(1024) NOT NULL,
  LAST_UPDATED_DATE DATE,
  constraint ADDRESS primary key (ID)
)
;

create table CONTACT_DETAILS
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  MOBILE VARCHAR(1024) NOT NULL,
  PHONE VARCHAR(1024) NOT NULL,
  EMAIL VARCHAR(1024) NOT NULL,
  PREFERRED_CONTACT VARCHAR(1024) NOT NULL,
  LAST_UPDATED_DATE DATE,
  constraint CONTACT_DETAILS primary key (ID)
)
;

create table PATIENT
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NHS_NUMBER VARCHAR(1024) NOT NULL,
  NAME_ID BIGINT NOT NULL,
  DOB DATE,
  ETHNICITY_ID BIGINT NOT NULL,
  GENDER_ID BIGINT NOT NULL,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0 NOT NULL,
  CONTACT_DETAILS_ID BIGINT NOT NULL,
  ADDRESS_ID  BIGINT NOT NULL,
  constraint PATIENT primary key (ID)
)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (CONTACT_DETAILS_ID) REFERENCES CONTACT_DETAILS(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (ETHNICITY_ID) REFERENCES ETHNICITY(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (GENDER_ID) REFERENCES GENDER(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (NAME_ID) REFERENCES NAME(ID)
;



create table REFERRER
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME_ID BIGINT NOT NULL,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0 NOT NULL,
  CONTACT_DETAILS_ID BIGINT NOT NULL,
  ADDRESS_ID  BIGINT NOT NULL,
  constraint REFERRER primary key (ID)
)
;

ALTER TABLE REFERRER ADD FOREIGN KEY (NAME_ID) REFERENCES NAME(ID)
;

create table REFERRAL
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  UBRN VARCHAR(1024) NOT NULL,
  TYPE VARCHAR(1024) NOT NULL,
  DESCRIPTION VARCHAR(5120) NOT NULL,
  CREATE_DATE DATE,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0 NOT NULL,
  USER_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  REFERRER_ID BIGINT NOT NULL,

  constraint REFERRAL primary key (ID)
)
;

ALTER TABLE REFERRAL ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID)
;

ALTER TABLE REFERRAL ADD FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
;

ALTER TABLE REFERRAL ADD FOREIGN KEY (REFERRER_ID) REFERENCES REFERRER(ID)
;
