create table NAME
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TITLE_ID BIGINT NULL,
  FIRST_NAME VARCHAR(1024)  NULL,
  MIDDLE_NAME VARCHAR(1024)  NULL,
  LAST_NAME VARCHAR(1024)  NULL,
  PREFERRED_NAME VARCHAR(1024)  NULL,
  LAST_UPDATED_DATE DATE,
  VERSION BIGINT NOT NULL,
  constraint NAME primary key (ID)
)
;

ALTER TABLE NAME ADD FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
;

create table ADDRESS
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LINE1 VARCHAR(1024)  NULL,
  LINE2 VARCHAR(1024)  NULL,
  LINE3 VARCHAR(1024)  NULL,
  CITY VARCHAR(1024)  NULL,
  COUNTY VARCHAR(1024)  NULL,
  COUNTRY VARCHAR(1024)  NULL,

  POST_CODE VARCHAR(1024)  NULL,
  LAST_UPDATED_DATE DATE,
  VERSION BIGINT NOT NULL,
  constraint ADDRESS primary key (ID)
)
;

create table CONTACT_DETAILS
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  MOBILE VARCHAR(1024)  NULL,
  PHONE VARCHAR(1024)  NULL,
  FAX VARCHAR(1024)  NULL,
  EMAIL VARCHAR(1024)  NULL,
  PREFERRED_CONTACT VARCHAR(1024)  NULL,
  LAST_UPDATED_DATE DATE,
  VERSION BIGINT NOT NULL,
  constraint CONTACT_DETAILS primary key (ID)
)
;

create table PATIENT
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NHS_NUMBER VARCHAR(1024)  NULL,
  NAME_ID BIGINT  NULL,
  DOB DATE,
  ETHNICITY_ID BIGINT  NULL,
  GENDER VARCHAR(1024)  NULL,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0  NULL,
  CONTACT_DETAILS_ID BIGINT  NULL,
  ADDRESS_ID  BIGINT  NULL,
  VERSION BIGINT NOT NULL,
  PRIMARY_SPOKEN_LANGUAGE VARCHAR(1024)  NULL,
  SECONDARY_SPOKEN_LANGUAGE VARCHAR(1024)  NULL,
  WRITTEN_LANGUAGE VARCHAR(1024)  NULL,
  INTREPRETER_REQUIRED BOOLEAN DEFAULT 0  NULL,
  ASSISTANCE_REQUIRED BOOLEAN DEFAULT 0  NULL,
  constraint PATIENT primary key (ID)
)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (CONTACT_DETAILS_ID) REFERENCES CONTACT_DETAILS(ID)
;

ALTER TABLE PATIENT ADD FOREIGN KEY (ETHNICITY_ID) REFERENCES ETHNICITY(ID)
;


ALTER TABLE PATIENT ADD FOREIGN KEY (NAME_ID) REFERENCES NAME(ID)
;



create table REFERRER
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME_ID BIGINT  NULL,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0  NULL,
  CONTACT_DETAILS_ID BIGINT  NULL,
  ADDRESS_ID  BIGINT  NULL,
  ROLE_ID  BIGINT  NULL,
  SPECIALITY VARCHAR(1024)  NULL,
  CLINIC_NAME VARCHAR(1024)  NULL,
  PRACTICE_CODE VARCHAR(1024)  NULL,
  VERSION BIGINT NOT NULL,
  constraint REFERRER primary key (ID)
)
;

ALTER TABLE REFERRER ADD FOREIGN KEY (NAME_ID) REFERENCES NAME(ID)
;

ALTER TABLE REFERRER ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
;

create table IGR_DESTINATION
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(1024)  NULL,
  REG_NAME VARCHAR(1024)  NULL,
  SPECIALITY VARCHAR(1024)  NULL,
  PRACTICE_NAME VARCHAR(1024)  NULL,
  REG_PRACTICE_NAME VARCHAR(1024)  NULL,
  REFERRED_TO VARCHAR(1024)  NULL,
  constraint IGR_DESTINATION primary key (ID)
)
;

create table REFERRAL
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  UBRN VARCHAR(1024)  NULL,
  TYPE VARCHAR(1024)  NULL,
  PROCESS_ID VARCHAR(1024)  NULL,
  DESCRIPTION VARCHAR(5120)  NULL,
  CREATE_DATE DATE,
  LAST_UPDATED_DATE DATE,
  ACTIVE BOOLEAN DEFAULT 0  NULL,
  PATIENT_ID BIGINT  NULL,
  REFERRER_ID BIGINT  NULL,
  IGR_DESTINATION_ID BIGINT  NULL,
  OPTLOCK BIGINT NOT NULL,
  CREATED_BY BIGINT  NULL,
  USER_ID BIGINT  NULL,
  STATUS VARCHAR(50)  NULL,
  constraint REFERRAL primary key (ID)
)
;


ALTER TABLE REFERRAL ADD FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
;

ALTER TABLE REFERRAL ADD FOREIGN KEY (REFERRER_ID) REFERENCES REFERRER(ID)
;

ALTER TABLE REFERRAL ADD FOREIGN KEY (IGR_DESTINATION_ID) REFERENCES IGR_DESTINATION(ID)
;







create table NOTE
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NOTE VARCHAR(5120)  NULL,
  USER_ID BIGINT  NULL,
  REFERRAL_ID BIGINT  NULL,
  LAST_UPDATED_DATE DATE,
  constraint NOTE primary key (ID)
)
;

ALTER TABLE NOTE ADD FOREIGN KEY (REFERRAL_ID) REFERENCES REFERRAL(ID)
;

ALTER TABLE NOTE ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID)
;


create table REFERRAL_STATUS
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT  NULL,
  REFERRAL_ID BIGINT  NULL,
  FROM_STATUS VARCHAR(50)  NULL,
  TO_STATUS VARCHAR(50)  NULL,
  LAST_UPDATED_DATE DATETIME,
  constraint REFERRAL_STATUS primary key (ID)
)
;

ALTER TABLE REFERRAL_STATUS ADD FOREIGN KEY (REFERRAL_ID) REFERENCES REFERRAL(ID)
;

ALTER TABLE REFERRAL_STATUS ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID)
;

