
DROP TABLE IF EXISTS USER;

create table USER
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_GUID VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  CREATED_DATE DATE NOT NULL ,
  DATE_OF_BIRTH DATE NOT NULL,
  USER_NAME  VARCHAR(255) NOT NULL,
  EMAIL_ADDRESS VARCHAR(255) NOT NULL,
  GENDER VARCHAR(1) DEFAULT 'U' NOT NULL,
  active BOOLEAN DEFAULT 0 NOT NULL,
  constraint PK_USER primary key (ID)
);


alter table USER add constraint USER_GUID_UQ unique (USER_GUID);


alter table USER add constraint EMAIL_ADDRESS_UQ unique (EMAIL_ADDRESS);

alter table USER add constraint USER_NAME_UQ unique (USER_NAME);


create table ROLE
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  active BOOLEAN DEFAULT 0 NOT NULL,
  constraint ROLE primary key (ID)
);

alter table ROLE add constraint ROLE_NAME_UQ unique (NAME);

create table USER_ROLE
(
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL
)
;

alter table USER_ROLE add constraint UR_UQ unique (USER_ID, ROLE_ID)
;

ALTER TABLE USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID)
;

ALTER TABLE USER_ROLE ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
;
