DROP TABLE IF EXISTS TITLE
;
DROP TABLE IF EXISTS ETHNICITY
;
DROP TABLE IF EXISTS GENDER
;

create table TITLE
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  constraint PK_TITLE primary key (ID)
)
;

create table ETHNICITY
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  constraint PK_ETHNICITY primary key (ID)
)
;

create table GENDER
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  constraint PK_GENDER primary key (ID)
)
;


