

create table COUNTRY
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,

  active BOOLEAN DEFAULT 0 NOT NULL,
  constraint PK_COUNTRY primary key (ID)
)
;

alter table COUNTRY add constraint COUNTRY_NAME_UQ unique (NAME);

create table STATE
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,

  active BOOLEAN DEFAULT 0 NOT NULL,
  constraint PK_STATE primary key (ID)
)
;

alter table STATE add constraint STATE_NAME_UQ unique (NAME)
;
create table COUNTRY_STATE
(
  COUNTRY_ID BIGINT NOT NULL,
  STATE_ID BIGINT NOT NULL
)
;

alter table COUNTRY_STATE add constraint CS_UQ unique (COUNTRY_ID, STATE_ID)
;

ALTER TABLE COUNTRY_STATE ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
;

ALTER TABLE COUNTRY_STATE ADD FOREIGN KEY (STATE_ID) REFERENCES STATE(ID)
;


create table CITY
(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  LATITUDE FLOAT(3,3),
  LONGITUDE FLOAT(3,3),

  active BOOLEAN DEFAULT 0 NOT NULL,
  constraint PK_CITY primary key (ID)
)
;

alter table CITY add constraint CITY_NAME_UQ unique (NAME)
;
create table STATE_CITY
(
  STATE_ID BIGINT NOT NULL,
  CITY_ID BIGINT NOT NULL
)
;

alter table STATE_CITY add constraint SC_UQ unique (STATE_ID, CITY_ID)
;

ALTER TABLE STATE_CITY ADD FOREIGN KEY (STATE_ID) REFERENCES STATE(ID)
;

ALTER TABLE STATE_CITY ADD FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)
;


